CREATE TABLE segment_historical_stats (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                          route_id BIGINT,
                                          segment_start_distance DOUBLE PRECISION,
                                          segment_end_distance DOUBLE PRECISION,

                                          hour_of_day INTEGER,
                                          day_of_week INTEGER,

                                          mean_time DOUBLE PRECISION,
                                          variance DOUBLE PRECISION,
                                          sample_count INTEGER
);

CREATE INDEX idx_segment_historical_stats_route_segment_hour_day
    ON segment_historical_stats (
                                 route_id,
                                 segment_start_distance,
                                 segment_end_distance,
                                 hour_of_day,
                                 day_of_week
        );