CREATE TABLE route_campaign_candidates (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                           route_id BIGINT NOT NULL,
                                           campaign_id VARCHAR(255) NOT NULL,

                                           entry_marker DOUBLE PRECISION NOT NULL,
                                           exit_marker DOUBLE PRECISION NOT NULL,
                                           active BOOLEAN NOT NULL,

                                               CONSTRAINT fk_campaign_candidate
                                               FOREIGN KEY (campaign_id)
                                                      REFERENCES campaigns(id)
                                                      ON DELETE CASCADE,

                                           CONSTRAINT fk_route_candidate
                                               FOREIGN KEY (route_id)
                                                   REFERENCES routes(route_id)
                                                   ON DELETE CASCADE
);

CREATE INDEX idx_route_campaign_candidates_route_id
    ON route_campaign_candidates (route_id);

CREATE INDEX idx_route_campaign_candidates_campaign_id
    ON route_campaign_candidates (campaign_id);

CREATE INDEX idx_route_campaign_candidates_route_campaign
    ON route_campaign_candidates (route_id, campaign_id);