CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE routes (
                        route_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        path geography(LineString, 4326),

                        route_name VARCHAR(128) NOT NULL
);