CREATE TABLE route_stops (
                             route_stop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             route_id BIGINT NOT NULL,
                             stop_sequence_number INTEGER NOT NULL,

                             stop_point geography(Point, 4326) NOT NULL,
                             distance_along_route DOUBLE PRECISION NOT NULL,
                             scheduled_time TIMESTAMP WITH TIME ZONE NOT NULL,

                             CONSTRAINT fk_route_stops_route
                                 FOREIGN KEY (route_id)
                                     REFERENCES routes(route_id)
);

CREATE INDEX idx_route_stops_route_id
    ON route_stops (route_id);

CREATE INDEX idx_route_stops_perf
    ON route_stops (route_id, stop_sequence_number ASC);