CREATE TABLE devices_routes (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                device_id VARCHAR(16) NOT NULL,
                                route_id BIGINT NOT NULL,

                                from_location VARCHAR(120) NOT NULL,
                                to_location VARCHAR(120) NOT NULL,
                                is_active BOOLEAN NOT NULL,

                                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                version BIGINT NOT NULL,

                                CONSTRAINT fk_devices_routes_device
                                    FOREIGN KEY (device_id)
                                        REFERENCES devices_credential(device_id),

                                CONSTRAINT fk_devices_routes_route
                                    FOREIGN KEY (route_id)
                                        REFERENCES routes(route_id)
);

CREATE INDEX idx_devices_routes_device_id
    ON devices_routes (device_id);

CREATE INDEX idx_devices_routes_route_id
    ON devices_routes (route_id);

CREATE INDEX idx_devices_routes_device_route
    ON devices_routes (device_id, route_id);

CREATE INDEX idx_devices_routes_route_active
    ON devices_routes (route_id, is_active);

CREATE INDEX idx_devices_routes_device_active
    ON devices_routes (device_id, is_active);

