CREATE TABLE geo_locations (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               device_id VARCHAR(16) NOT NULL,
                               capture_session_id UUID NOT NULL,
                               sequence_number BIGINT NOT NULL,

                               positions JSONB,

                               generated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                               created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                               updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                               version BIGINT NOT NULL
);

CREATE INDEX idx_geo_locations_device_capture_session
    ON geo_locations (device_id, capture_session_id);

CREATE INDEX capture_session_id
    ON geo_locations (capture_session_id);