CREATE TABLE heartbeats (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            device_id VARCHAR(16) NOT NULL,
                            route_id BIGINT NOT NULL,
                            distance_along_route DOUBLE PRECISION NOT NULL,
                            heartbeat BOOLEAN NOT NULL,
                            received_at TIMESTAMP WITH TIME ZONE NOT NULL,

                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            version BIGINT NOT NULL
);

CREATE INDEX idx_heartbeats_device_received_at
    ON heartbeats (device_id, received_at);

CREATE INDEX idx_heartbeats_device_on_route
    ON heartbeats (device_id, route_id);