CREATE TABLE periodic_allocation (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   device_id VARCHAR(255) NOT NULL,
                                   campaign_id VARCHAR(255) NOT NULL,

                                   start_window TIMESTAMP WITH TIME ZONE NOT NULL,
                                   end_window TIMESTAMP WITH TIME ZONE NOT NULL,

                                   date_of_allocation DATE,
                                   local_start_time TIME,
                                   local_end_time TIME,

                                   allocated_plays INTEGER NOT NULL
);

CREATE INDEX idx_periodic_allocation_device_start_end
    ON periodic_allocation (device_id, start_window, end_window);

CREATE INDEX idx_periodic_allocation_device_end
    ON periodic_allocation (device_id, end_window);

CREATE INDEX idx_periodic_allocation_device_start
    ON periodic_allocation (device_id, start_window);